### PR TITLE
feat: shopping-list example template

### PR DESCRIPTION
**Pull request by kasyap1234**
example template for shopping list using Encore.go

### CODE REVIEW

**Comment by eandre** [comment]
Hey @kasyap1234, I appreciate you taking the time to write this up. For the moment we're focusing primarily on examples that showcase some new aspect of Encore that hasn't previously been covered, and this example doesn't seem to qualify as it's mainly demonstrating functionality already covered by existing examples. For that reason I'm going to close this PR. Hope you understand where I'm coming from here.

**Comment by kasyap1234** [comment]
Ok got it , thanks 👍,
Btw I am working on       stripe template (integration ) . It was mentioned in 2022 , is it still relevant ?

**Comment by eandre** [comment]
It could be, but a Stripe integration is also quite complex and is an area that is extremely important to get right. We'd need to make sure it is of such high quality in terms of security, generality, etc, in order to be able to accept it and recommend for use as a starting point for others. So whether it makes sense for integrating here depends on a lot of those factors.

**Comment by kasyap1234** [comment]
Understood

**Pull request closed without merging**
